chore: update syntax

diff --git a/.github/workflows/create-pre-release.yml b/.github/workflows/create-pre-release.yml
--- a/.github/workflows/create-pre-release.yml
+++ b/.github/workflows/create-pre-release.yml
@@ -30,7 +30,16 @@ jobs:
       - name: Extract branch ticket name
         id: ticket_name
         run: |
-          echo "${{ github.event.head_commit.message }}" | grep -i -o 'BC-[0-9]\+'
+          RESULT=$(echo "${{ github.event.head_commit.message }}" | grep -i -o 'BC-[0-9]\+' || echo "")
+          if [ "$RESULT" != "" ]; then
+              echo "Branch name: $RESULT"
+              echo "Ticket name: $(echo "${{ github.event.head_commit.message }}" | grep -i -o 'BC-[0-9]\+' | head -n 1 | tr '[:lower:]' '[:upper:]')"
+              echo "TICKET_NAME=$(echo "${{ github.event.head_commit.message }}" | grep -i -o 'BC-[0-9]\+' | head -n 1 | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT
+          else
+              echo "Invalid commit message, not containing a ticket name (BC-XXXX)"
+              echo "${{ github.event.head_commit.message }}"
+              echo "TICKET_NAME=$(echo "")" >> $GITHUB_OUTPUT
+          fi
       - name: Automated Version Bump
         uses: phips28/gh-action-bump-version@master
         env:
